### ISSUE TITLE
Unable to invoke partition_pdf bc patches is not found

### ISSUE THREAD

**Issue by dimroc** [Unstructured-IO/unstructured-inference#99]
See error below when using most recent version: 0.4.3. I suspect it is because `patches` is not a package.

```python
elements = partition_pdf(local_filename, ocr_languages="eng")
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/unstructured/partition/pdf.py", line 207, in _partition_pdf_or_image_local
    from unstructured_inference.inference.layout import (
  File "/usr/local/lib/python3.9/site-packages/unstructured_inference/inference/layout.py", line 20, in <module>
    from unstructured_inference.patches.pdfminer import parse_keyword
ModuleNotFoundError: No module named 'unstructured_inference.patches'
```

**Comment by dimroc** [comment]
cc @qued

**Comment by qued** [comment]
I've verified the issue and your fix. Thanks for submitting this. I'm going to fasttrack your PR.

**Comment by qued** [comment]
Closing as resolved by the mentioned PR.
